### ISSUE TITLE
Please make it for us to be able to save

### ISSUE THREAD

**Issue by sdcervi** [sdcervi/PokeDexApp#2]
Submitted by c*****@gmail.com on 13 April 2021.

Currently working on this, but progress is slow because I have a full-time job and have hit some roadblocks in implementing this feature.

- Can create user login and have it work, using code from an example online
- When I try to add a field to the database, it breaks the login feature somehow
- Not sure how best to store/access/edit user dexes

**Comment by sdcervi** [comment]
New submission by j*****@gmail.com on 21 November 2021.

"Hi, Is there any chance you're still working on developing this? In particular, I'd want to make an account or host my own server so that I Can save my progress."

**Comment by sdcervi** [comment]
Current features required:

- [ ] Drop-down in nav bar to allow login
- [ ] Secondary navbar with user stats/profile/logout link only visible after login
- [ ] SSL certificate

Nice-to-haves:

- [ ] Single sign-on via Google, Facebook, etc.

**Comment by sdcervi** [comment]
Potentially doable to save data into local storage. Downside is that users may lose data if they clear cookies or use a different browser. Export/import from CSV/json?

**Comment by sdcervi** [comment]
Can implement via localStorage. Still need to test export/import though, and should either have a Save Changes button, or save every time viewport is re-written

**Comment by pranavchary** [comment]
Have you considered using a free RTDB like Firebase for reading/writing data quickly?

**Comment by sdcervi** [comment]
> Have you considered using a free RTDB like Firebase for reading/writing data quickly?

I've heard of that but haven't researched it yet since I'm still figuring out the correct way to build the data structure itself. Currently I'm using MySQL to store the Pokemon data, but I'm open to alternatives for that and for user data. Ideally someone with more experience and knowledge of this would be working on it so that I don't end up building myself a half-baked system that doesn't follow best practices.
