### ISSUE TITLE
User data loads very slowly

### ISSUE THREAD

**Issue by sdcervi** [sdcervi/PokeDexApp#37]

**Comment by runburg** [comment]
Do you know the source of this? I'm seeing this on my development server and I think it's just the sprites? Is there a better way to do the lazy loading?

**Comment by sdcervi** [comment]
It's the Firebase authentication function. I'm not sure how to speed it up, still researching. As far as lazy loading images, I'm using the built-in browser functionality for that but I'm open to other options.

This shows up on the preview URL but not on my localhost server with the firebase emulator. I think it has something to do with how it accesses the data.

**Comment by sdcervi** [comment]
So after a bit of investigation, it seems to load nice and quick on mobile, but it's desktop where it's slow.

**Comment by sdcervi** [comment]
Note for self: This seems to be browser-related. It's slow as molasses on Chrome on my laptop, but zippy fast in Chrome Incognito Mode, other browsers, and on my other devices. Resetting Chrome to default settings didn't have a significant effect.

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9577-user-data-loads-very-slowly/
