### ISSUE TITLE
List view

### ISSUE THREAD

**Issue by runburg** [sdcervi/PokeDexApp#38]
So my attempts at list view are on a new branch. 

It doesn't look great ~yet~ but I want to see what you think about this before I go ahead with it @sdcervi.

Let me know what you think.

**Comment by sdcervi** [comment]
Putting this here for my own task tracking

- [ ] Set up list view/grid view toggle, localStorage flag
- [ ] Generate entire set of sprites including all alts
- [x] Read user data and apply stored state to dex sprites
- [ ] Set up toggling between states (uncaught, trade, place, caught)
