### ISSUE TITLE
Adding settings panel

### ISSUE THREAD

**Issue by runburg** [sdcervi/PokeDexApp#39]
The idea would be to have a configuration panel (modal or something) that would allow the user to configure which dexes are shown (e.g. just shiny nat dex and shiny alt forms) if they didn't want all of them.

**Comment by sdcervi** [comment]
I actually have a spot for settings in the Profile page. Would that work?

**Comment by runburg** [comment]
Awesome so I configure firebase so I can use the login features.

Can you point me in the direction of where/how user data is stored and how I can access different settings/store user data?

**Comment by sdcervi** [comment]
Just had another user request for this feature so I'll see about packaging it together with the list view update.

**Comment by sdcervi** [comment]
Finished a first pass at this, planning to push to production with List View when we finish that out.
