### ISSUE TITLE
Gigantamax status

### ISSUE THREAD

**Issue by sdcervi** [sdcervi/PokeDexApp#41]
Requested by Ivan: "You should consider adding gigantamax pokemon as their own tab."

Given that as of right now, Pokemon Home doesn't recognize Gigantamax-capable pokemon as visually distinct and separate entities from normal pokemon (other than the badge on the info panel) I won't be adding this feature.  I'm keeping a ticket here for it though in case that functionality becomes available in the future on Pokemon Home.

**Comment by Garfieldwxg55** [comment]
If I remember correctly, although the Pokémon don't show as different in the HOME menu (except for the G-Max badge), it does register Pokédex entries for them that would not have been otherwise accessible if they had not been deposited. Thanks for reading!

**Comment by sdcervi** [comment]
I think I'm going to try to add this under another alt forms section, which people can use or ignore as they please. Should release in the next content update soon.

**Comment by sdcervi** [comment]
Home also tracks Mega, apparently, so I'll need to work up a list of both form types.

**Comment by sdcervi** [comment]
Note to also add Alpha status to tracking

**Comment by sdcervi** [comment]
Note to also add Terastal status

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9581-add-gigantamaxmegaalphaterastal-as-an-option-in-the-pop-up-status-menu/
