### ISSUE TITLE
New Pokémon from Legends: Arceus don't have their HOME sprites

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#45]
I've been using this Pokédex App for while and have enjoyed it, however, I noticed that the newly added Pokémon from Legends: Arceus (Wyrdeer, Kleavor, Ursaluna, male and female Basculegion, Sneasler, Overqwil, and both the Incarnate and Therian of Enamorus) don't have their Pokémon HOME sprites, but instead their sprites from the actual Legends: Arceus game. Oddly enough, the new Hisuian forms of existing Pokémon don't seem to have this problem and use their HOME sprites. Thanks for reading :)

**Comment by sdcervi** [comment]
Thanks for catching this!  I haven't had a lot of time to work on this lately, but I'll get these corrected in the upcoming new feature release.

**Comment by Garfieldwxg55** [comment]
No problem, thanks for fixing!

**Comment by sdcervi** [comment]
Fixed and will deploy with list view
