### ISSUE TITLE
Fused forms for Kyurem, Necrozma, and Calyrex are listed even though they can't be deposited in HOME

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#46]
Hi, so I was looking at the list of alternate forms, and I noticed that the fused forms for Kyurem, Necrozma, and Calyrex were listed even though they can't be deposited in Pokémon HOME. Just a small error, thanks for reading!

**Comment by sdcervi** [comment]
Thanks! I'll add this to the fix list for the next release.

**Comment by Garfieldwxg55** [comment]
That's great to hear, thanks again!

**Comment by sdcervi** [comment]
Fixed and will release with list view
