### ISSUE TITLE
Pokémon could be able to appear in several categories?

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#49]
Hi, this is more just an idea of mine, but I was looking at White-Stripped Basculin, and I noticed that it was in the forms section and not the regional forms section. Which is funny, because White-Stripped Basculin is considered a regional form by HOME, so it counts for the regional form section, but it's also a third form of Basculin, akin to the Red-Stripped and Blue-Stripped forms. 
Then I started thinking about the sex-difference for Hisuian Sneasel. It's a regional form, so it definitely belongs in the regional form section, but it also has a sex-difference (the only regional to do so), so it also belongs in the sex difference section, whereas right now the sex-difference is displayed in the regional forms area, which could be a problem for people who are not going for a form-dex.
So I was thinking, what if Pokémon could be listed in multiple places, for example, if White-Stripped Basculin could be displayed in both the regional forms section and the forms section. Or if Hisuian Sneasel could be displayed both in the regional forms section and the sex-difference section, perhaps next to Johtonian Sneasel. This could also make it so if a sex-difference/alternate form of a Pokémon is registered, it would also register in the main Living Dex. This was just an idea I had and I'm not sure it's possible, thanks for reading!

**Comment by sdcervi** [comment]
I'll have to think on this to come up with the best way to implement it. Definitely food for thought!

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9584-pokemon-could-be-able-to-appear-in-several-categories/
