### ISSUE TITLE
Progress was deleted with List View

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#51]
Hi, I just tested out the new list view, and I noticed that all my progress was deleted. It's not a big deal, I refilled it out, but I thought I'd just post it here. Thanks for reading :)

**Comment by sdcervi** [comment]
Yeah, there's a bug I'm currently working on fixing. As far as I can tell there's been no data loss, it's just not getting read from the database correctly.

**Comment by sdcervi** [comment]
Ok, I think I have this fixed (for the third time...) but I'll leave this ticket open until the other people who have reported the problem confirm it's working correctly for them.

**Comment by Garfieldwxg55** [comment]
It's definitely working properly for me, so thanks :)
