### ISSUE TITLE
Hisuian forms are missing

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#52]
Hi, I was testing out the new list view, and refilling out my Dex, and I noticed that the box for the Hisuian forms were missing. I did notice that White-Stripped Basculin was still listed, albeit in the Alt forms section. Thanks for reading :)

**Comment by sdcervi** [comment]
Thanks for catching that, I'll add it to the fix list.

**Comment by sdcervi** [comment]
Hisuian alts were missing because I fixed it in the main branch but not in the list-view branch.  Gotta love merge conflicts.
