### ISSUE TITLE
[List View] A lot of Pokémon have three gender forms for some reason

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#53]
Hi, sorry if I'm posting too many issues, if you already know about this stuff just let me know and I'll stop posting, but I noticed that a lot of Pokémon have three gender forms (the Bidoof, Starly, and Shinx lines as an example). Once again, sorry if you already know about this, thanks for reading :)

**Comment by sdcervi** [comment]
I'm not seeing this on either my testing instance or the live version.  Can you upload a screenshot please?

**Comment by Garfieldwxg55** [comment]
Sorry for the delay, I just tested it again, and I think that it might have been a mistake on my end, I was using it on my phone  and I think I misunderstood the primary and gender form labels, sorry for the false issue :)
