### ISSUE TITLE
Some alt forms appear in the wrong order

### ISSUE THREAD

**Issue by FivesBlue** [sdcervi/PokeDexApp#54]
Hi, I just completed my National Form Dex for the Gala region, and I noticed that some of the Alt forms appear in the wrong order. Urshifu's forms are reversed, and the Alcremie are in a different order than the HOME Pokédex (both the sweets and the swirls). I suppose this might also affect Pokémon like Vivillon with lots of alt forms too. 
Thanks for reading :)

**Comment by sdcervi** [comment]
Good catch! I'll add this to the fix list next time I'm making changes.

**Comment by sdcervi** [comment]
- [ ] Urshifu
- [ ] Alcremie
- [ ] Vivillon

**Comment by sdcervi** [comment]
Will publish with next update (Scarlet/Violet adds)
