### ISSUE TITLE
Enhancement: Add way to limit what generations you're completing

### ISSUE THREAD

**Issue by Midnight145** [sdcervi/PokeDexApp#58]
It'd be nice to have a way to select either what game you're completing dex for, or limit what generations of Pokemon you care about, so when looking at the percentage in your profile it shows an accurate percentage (eg. X out of 493 if you're hunting up to gen 4) instead of the full 905, as well as all of the other "boxes" being hidden on the main page.

**Comment by sdcervi** [comment]
Good suggestion! I originally aimed this at Home users wanting to do a full living dex, but this can definitely be in the feature roadmap.

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9587-add-way-to-limit-what-generations-youre-completing/
