### ISSUE TITLE
Firebase Google Sign-in error

### ISSUE THREAD

**Issue by Midnight145** [sdcervi/PokeDexApp#66]
This is very possibly user error and I'm just smallbrain

When pressing "Sign in with Google" on the login page, I get an error saying:
"Firebase: Error (auth/api-key-expired.-please-renew-the-api-key.)."
![image](https://github.com/sdcervi/PokeDexApp/assets/23142346/41827e0f-a7b8-41fd-80e7-c27592668129)

**Comment by sdcervi** [comment]
Nope, that's not smallbrain, at least not on your part. I borked the API key.

**Comment by Midnight145** [comment]
Ahh, alright--I revoked a few app passwords the other day, so I wasn't sure if I had broken something in my Google account

**Comment by sdcervi** [comment]
I was a doof and had my API key in one of the code files for this, forgot to remove it before committing changes. I know better now...

**Comment by Midnight145** [comment]
Ahh, yep, I've done that a time or two. Want me to go ahead and close this?

**Comment by sdcervi** [comment]
Nah, I need to get it fixed properly. I just reverted to the previous key as a band-aid, I'll do it properly in the morning after I've (hopefully) slept some.

**Comment by Midnight145** [comment]
Alright, thank you so much!

**Comment by sdcervi** [comment]
After some research, I'm leaving the old API key active, and just applying restrictions to which domains can make auth requests. Should be working as expected now!
