### ISSUE TITLE
Own Tempo Rockruff Considered Different Form in Home

### ISSUE THREAD

**Issue by LunaArcticWolf** [sdcervi/PokeDexApp#68]
Didn't see this mentioned but Rockruff with the Own Tempo Ability is treated as a different form. Was wondering if this could be added.

Pictures below of both forms:
![Screenshot_20230721-083848](https://github.com/sdcervi/PokeDexApp/assets/140173709/36b53007-5db6-4376-9148-a84cc1955d41)
![Screenshot_20230721-083851](https://github.com/sdcervi/PokeDexApp/assets/140173709/e011cc85-2c68-4fb0-b599-dfc06918364e)

**Comment by sdcervi** [comment]
Good catch! Any ideas for what I should label the non-Own Tempo alt? Normal or Standard or something like that?

**Comment by LunaArcticWolf** [comment]
Maybe the non-Own Tempo should be the standard one in the national dex while the Own tempo would go under alt forms. Since the own tempo was originally an event mon.

**Comment by sdcervi** [comment]
I've added Rockruff's Own Tempo alt form to the dex. Thanks!
