### ISSUE TITLE
Duplicate Pokemon forms

### ISSUE THREAD

**Issue by darkfire006** [sdcervi/PokeDexApp#76]
Currently all forms are listed in the forms section, it would be nice to atleast have an option to hide one form per pokemon
ex: hide the male forms in the gendered section, hide normal rotom form but leave the Appliance forms, etc

Since one of each form will be in the main dex it makes it very redundant for tracking and less easy to match against what I have in my boxes

**Comment by sdcervi** [comment]
At this point, that would require completely re-factoring how the boxes and pokemon are added to the page. I'll keep this open to be voted on at a later date by supporting subscribers, though.

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9596-duplicate-pokemon-forms/#comment-10627
