### ISSUE TITLE
Icy Snow Scatterbug no longer looks different in the latest version of Pokemon Home

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#78]
Hi, so I actually have (nearly) all of the Scatterbug forms, and I noticed that in one of the recent HOME updates (think it was the Teal Mask but not sure) that the Icy Snow Scatterbug no longer has a different sprite compared to the rest of the Scatterbugs. To fix this, I guess you could either make all the Scatterbugs different forms, but then you'd have to worry about all the other technical forms as well. Alternatively, you could just make Scatterbug no longer have an alternate form, like it used to be.

Thanks for reading!

**Comment by sdcervi** [comment]
Looks like they fixed it in an update! I'll get that adjusted in the alt forms with the next release.

**Comment by Garfieldwxg55** [comment]
Thanks!

**Comment by sdcervi** [comment]
I've updated the main form of Scatterbug to be correct, and removed the alt forms. It should be visible on the live site soon.
