### ISSUE TITLE
Pikachu and Rockruff's default forms don't show in the Alt forms menu

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#79]
Hi, so I've been using PokeDexApp for awhile, and I really enjoy it. However, I noticed a slight inconsistency with the alt forms for Pikachu and Rockruff in the alt forms menu. Unlike many of the other alt forms (such as Paldean Tauros, Deoxys, Rotom, Furfrou, and Ursaluna) who, alongside their more obscure alternate forms, they also have their normal/default/common form listed in the alt forms menu. However, Pikachu and Rockruff seem to be the only two Pokemon that don't have every one of their forms listed in the alt forms menu. 

Is there any chance this might be possible to fix?

Thanks again!

**Comment by sdcervi** [comment]
Good catch! I'll roll this into the next release.

**Comment by Garfieldwxg55** [comment]
That's great to hear!

**Comment by sdcervi** [comment]
Fixed, and should be up on the live site soon.
