### ISSUE TITLE
All of Zygarde's 4 forms are not listed in the alt forms menu

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#80]
Hi, I really enjoy using PokeDexApp, and use it to track the progress of my National Living Form Dex, however, I noticed only two of Zygarde's four forms are listed. Zygarde has four forms, the 10% form with Aura Break, the 50% form with Aura Break, the 10% form with Power Construct, and the 50% form with Power Construct. The 10% and 50% forms with Power Construct are able to transform into the 100% form while in battle when their HP is below, and the 10% and 50% forms with Aura Break "Break" Xerneas and Yveltal's Aura abilities when in battle with them. 

As far as I can tell, these different abilities are not different abilities belonging to the same Pokemon, but entirely different forms, similar to Rockruff. So I was curious if it might be possible to add all forms of Zygarde to PokeDexApp, as it'd really help me track my National Living Form Dex progress!

Thanks again!

**Comment by sdcervi** [comment]
Home only seems to have three sprites, according to Bulbapedia: https://bulbapedia.bulbagarden.net/wiki/Zygarde_(Pok%C3%A9mon)#Sprites

**Comment by Garfieldwxg55** [comment]
Ah yeah, I think it's an Own Tempo Rockruff type thing, where they look the same (including the sprite), but when you go into them you can see the separate form from the ability!
