### ISSUE TITLE
Sinistea and Polteageist's Phony and Antique forms don't display the HOME differentiating sprites even though Poltchageist and Sinistcha do

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#81]
Hi, this is just a little issue I noticed, but I saw that the differentiation sprites for Sinistea and Polteageist's different forms from HOME 
aren't used in the alt forms tab, even though Poltchageist and Sinistcha's equivalent alt forms.

Thanks for reading, and thanks for making this app!

**Comment by Garfieldwxg55** [comment]
Great, looking forward to it!

**Comment by sdcervi** [comment]
Fixed Thank you. Should be up on the live site soon.
