### ISSUE TITLE
A few alt forms are listed out of order

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#82]
Hi, I was looking at my HOME, and I noticed a few alt forms were listed as out of order in PokeDexApp compared to HOME:

Unown: at the end ?, !
Should be: at the end !, ?

Rotom: Normal, Fan, Frost, Heat, Mow, Wash
Should be: Normal, Heat, Wash, Frost, Fan, Mow

Flabebe line: Red, Orange, Yellow, Blue, White
Should be: Red, Yellow, Orange, Blue, White

Oricorio: Balle, Pau, Pom Pom, Sensu
Should be: Balle, Pom Pom, Pau, Sensu

Squawkabily: Blue, Green, White, Yellow
Should be: Green, Blue, Yellow, White

I also noticed that Furfrou was listed out of order, although I wasn't able to confirm the exact order since I don't have all the Furfrou forms yet.

Is there any chance this could be fixed? Thanks!

**Comment by sdcervi** [comment]
I'll get this fixed in the next release. Hoping to do that within the next few weeks ideally.

**Comment by Garfieldwxg55** [comment]
Great, looking forward to it, thanks again!

**Comment by Garfieldwxg55** [comment]
BTW, just did a bit more research and discovered a few more forms which were out of order:

Furfrou: Natural, Dandy, Debutante, Diamond, Heart, Kabuki, La Reine, Matron, Pharaoh, Star
Should be: Natural, Heart, Star, Diamond, Debutante, Matron, Dandy, La Reine, Kabuki, Pharaoh

Pumpkaboo/Gourgeist: Small, Average, Large, Super
Should be: Average, Small, Large, Super

Lycanroc: Midday, Dusk, Midnight
Should be: Midday, Midnight, Dusk

Hope this helps!

**Comment by sdcervi** [comment]
For Pumpkaboo, Zygarde, and Lycanroc, I decided to go with what I felt was a more logical sequence to the forms rather than what was listed in Home or the various databases.

Especially for Pumpkaboo/Gourgeist, those are sequential by size. It makes sense from a programming perspective that Average would be Form 0 in the list, but it kind of bugged me visually to have it before the Small size.

**Comment by Garfieldwxg55** [comment]
Ahh right, gotcha, that makes sense!

**Comment by sdcervi** [comment]
- [ ] Unown
- [ ] Rotom
- [ ] Flabebe
- [ ] Oricorio
- [ ] Squawkabily
- [ ] Furfrou

**Comment by sdcervi** [comment]
Fixes done, and should be on the live site soon. Thanks!
