### ISSUE TITLE
Should White-Stripped Basculin be considered a Regional Form?

### ISSUE THREAD

**Issue by Garfieldwxg55** [sdcervi/PokeDexApp#83]
So this is more of a question, but I was curious if White-Stripped Basculin should be considered a Hisuian form, or just a regular alternate form?

There's a far bit of evidence against, like the fact that it's not treated as a regional form in Scarlet/Violet and GO. However, perhaps most importantly for this tracker, is that it seems to be treated as a regional form in HOME, showing alongside the other Hisuian forms when the PokéDex is filtered by Hisuian form.

There's a full breakdown of the evidence for/against on Bulbapedia:
https://bulbapedia.bulbagarden.net/wiki/Hisuian_form

Just thought I'd put this out there!

**Comment by sdcervi** [comment]
I think based on game mechanics I'm going to keep it as a regular alt form since it doesn't require an Everstone for breeding and it can be found in Kitakami in the wild.

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9597-should-white-stripped-basculin-be-considered-a-regional-form/
